//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProjeOrnek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class calisanlar
    {
        public int calisanNo { get; set; }
        public string adSoyad { get; set; }
        public string adres { get; set; }
        public string telefon { get; set; }
        public string maas { get; set; }
        public int departmanNo { get; set; }
    }
}
