//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProjeOrnek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class firmalar
    {
        public int firmaNo { get; set; }
        public string firmaAdi { get; set; }
        public string firmaAdres { get; set; }
        public string firmaTelefon { get; set; }
        public int plazaNo { get; set; }
    }
}
